### PR TITLE
Test against the latest ruby

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Maybe you should actually add all supported major rubies in here?

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I also observed that you use `TargetRubyVersion: 2.3` in `.rubocop.yml`, but `required_ruby_version = '~> 2.1'` in gemspec. This is dangerous because you might accidentally break support by using newer rubies features, specially since you don't test all versions. You should probably reconcile that too.

**Comment by deivid-rodriguez** [comment]
Any thoughts here @glebm? I'll gladly make the extra changes I commented if you agree with them!

**Comment by glebm** [comment]
Sounds good to me and let's remove support for older rubies. https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/

**Comment by deivid-rodriguez** [comment]
Absolutely, let me add those changes!

**Comment by deivid-rodriguez** [comment]
It's ready, have a look! I also fixed some TODO's were meant to be fixed after dropping 2.2 support. I fully trusted rubocop auto-correction here (plus manually fixed the non-autocorrectable `Style/NumericPredicate` offenses. I looked at the generated diff and looks correct to me?

**Comment by deivid-rodriguez** [comment]
Also, I didn't touch the changelog because I noticed that you normally update it at relase time.

**Pull request merged**
