### PR TITLE
Keep order rebased

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
I rebased #147 and added some specs!

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I applied your review comment feedback in https://github.com/glebm/i18n-tasks/pull/147#discussion_r43571503, but tests started failing. Not sure if it's the test, the implementation or the review comment that's wrong :question:

**Comment by deivid-rodriguez** [comment]
@glebm Friendly ping! :)

**Comment by glebm** [comment]
Thanks!

**Comment by deivid-rodriguez** [comment]
Thanks to you! :smiley:

**Pull request merged**
