### PR TITLE
using %{key} in add_missing interpolations

### PR DESCRIPTION
**Pull request by stijnster**
Hi there,

thanks for your awesome work on this gem.

When using it, we noticed that using the "human_key" is not always optimal for us. So I've added the ability to add a "%{key}" value which will add the node's full_key in the interpolated value.

I've added tests for this new feature and they all turn green.

Please consider this feature to add to the main repository.

Kind regards,

Stijn

### CODE REVIEW

**Comment by stijnster** [comment]
Of course, if you add this options to the main repo, I'll be happy to extend the current documentation ;)

**Comment by glebm** [comment]
@stijnster Thank you for your contribution!  :+1:

**Comment by glebm** [comment]
Release in v0.8.7! Docs updated

**Comment by stijnster** [comment]
Awseome stuff! Thanks!!

**Pull request merged**
