### PR TITLE
Add default_i18n_subject AST matcher

### LINKED ISSUE #500: For mailers: default_i18n_subject is reporting as missing
```ruby
class UserMailer < ApplicationMailer
  def email_verification
    @user       = params[:user]
    @locale     = @user.locale

    I18n.with_locale(@locale) do
      mail to: @user.email, subject: default_i18n_subject
    end
  end

  def invitation_instructions
    @user       = params[:user]
    @locale     = @user.locale

    I18n.with_locale(@locale) do
      mail to: @user.email, subject: default_i18n_subject
    end
  end

  def password_reset
    @user       = params[:user]
    @locale     = @user.locale

    I18n.with_locale(@locale) do
      mail to: @user.email, subject: default_i18n_subject
    end
  end

  def passwordless
    @user       = params[:user]
    @locale     = @user.locale

    I18n.with_locale(@locale) do
      mail to: @user.email, subject: default_i18n_subject
    end
  end
end
```

```yml
en:
  user_mailer:
    email_verification:
      subject: Verify your email
    invitation_instructions:
      subject: Invitation instructions
    password_reset:
      subject: Reset your password
    passwordless:
      subject: Your sign in link
```

I was expecting the task to pick up on the subject here?

### PR DESCRIPTION
**Pull request by Bilka2**
Resolves #500.

### CODE REVIEW

**Comment by glebm** [comment]
Thanks!

**Comment by Bilka2** [comment]
Thank you! Would it be possible to get a release with this?

**Comment by mhenrixon** [comment]
Dang! That makes me super happy!!

**Comment by glebm** [comment]
> Thank you! Would it be possible to get a release with this?

For new features, I prefer if people try out the unreleased version for a few weeks and report / fix any bugs they may find.

**Pull request merged**
