### PR TITLE
Ignore the "adding children to leaf" warning for keys that are discovered in source.

### PR DESCRIPTION
**Pull request by jfly**
See https://github.com/glebm/i18n-tasks/issues/158#issuecomment-278515453.

I'm not very familiar with this codebase, but tests still pass!. @glebm, is this close to what you had in mind?

### CODE REVIEW

**Comment by glebm** [comment]
@jfly Yes, this looks OK, thank you. Does this work in your case?

**Comment by jfly** [comment]
Ah, good question, it did not =(

I've fixed this in https://github.com/glebm/i18n-tasks/pull/228/commits/4f65248d0e8d4e834d15dd289f60708a9f2955e6, along with a test.

With the current version of `i18n-tasks`:

```
~/gitting/worldcubeassociation.org/WcaOnRails @kaladin> bundle exec i18n-tasks unused
warning: parser/current is loading parser/ruby24, which recognizes
warning: HEAD-compliant syntax, but you are running 2.4.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
i18n-tasks: [WARN] 'faq.answers' was a leaf, now has children (value <- scope conflict)
Unused keys (2) | i18n-tasks v0.9.11
+--------+-----------------------------+---------------------------+
| Locale | Key                         | Value                     |
+--------+-----------------------------+---------------------------+
|   ru   | registrations.events        | Дисциплины                |
|   ru   | users.edit.preferred_events | Предпочитаемые дисциплины |
+--------+-----------------------------+---------------------------+
```

With my changes:

```
~/gitting/worldcubeassociation.org/WcaOnRails @kaladin> ruby -I~/tmp/i18n-tasks/lib ~/tmp/i18n-tasks/bin/i18n-tasks unused
/usr/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/usr/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
Unused keys (2) | i18n-tasks v0.9.11
+--------+-----------------------------+---------------------------+
| Locale | Key                         | Value                     |
+--------+-----------------------------+---------------------------+
|   ru   | registrations.events        | Дисциплины                |
|   ru   | users.edit.preferred_events | Предпочитаемые дисциплины |
+--------+-----------------------------+---------------------------+
```

**Comment by jfly** [comment]
Unfortunately, it looks like rubocop failed in the last build: https://travis-ci.org/glebm/i18n-tasks/jobs/200283068#L512.

I could work around this, but I'd like to wait to hear your thoughts on the latest implementation first. If we're going to do it differently, then I don't think it's worth the effort to please rubocop right now.

**Comment by glebm** [comment]
@jfly This implementation looks fine. 👍

**Comment by jfly** [comment]
Ok, sweet! I can easily address the line length issues, but I can't easily fix:

```
lib/i18n/tasks/data/tree/node.rb:13:19: C: Metrics/ParameterLists: Avoid parameter lists longer than 5 parameters.
    def initialize(key:, value: nil, data: nil, parent: nil, children: nil, warn_about_add_children_to_leaf: true)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

How would you like me to address this? Easiest fix is to change `.rubocop.yml` to not check this.

**Comment by glebm** [comment]
Best just ignore it in that particular case, so that we still get warnings elsewhere:

```ruby
# rubocop:disable Metrics/ParameterLists
def ...
end
# rubocop:enable Metrics/ParameterLists
```

**Pull request merged**
